description = "Ubuntu 24.04 Noble Numbat base image with no buildpacks included. To use, specify buildpacks at build time."

[build]
  image = "docker.io/paketobuildpacks/ubuntu-noble-build:0.0.57"

[lifecycle]
  version = "0.21.4"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/ubuntu-noble-run:latest"

[stack]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
