description = "Ubuntu 24.04 Noble Numbat base image with buildpacks for Java, Node.js, .NET, Nginx, HTTPD and Procfile"

[build]
  image = "docker.io/paketobuildpacks/ubuntu-noble-build:0.0.53"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java-native-image:14.0.0"
  version = "14.0.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java:21.1.0"
  version = "21.1.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/nodejs:10.0.5"
  version = "10.0.5"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/dotnet-core:4.0.4"
  version = "4.0.4"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/procfile:5.12.1"
  version = "5.12.1"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/web-servers:4.0.4"
  version = "4.0.4"

[lifecycle]
  version = "0.21.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "14.0.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "21.1.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/web-servers"
    version = "4.0.4"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "10.0.5"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core"
    version = "4.0.4"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.12.1"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/ubuntu-noble-run:latest"

[stack]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
