description = "Ubuntu 24.04 Noble Numbat base image with buildpacks for Java, Node.js, .NET, Nginx, HTTPD and Procfile"

[build]
  image = "docker.io/paketobuildpacks/ubuntu-noble-build:0.0.47"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java-native-image:13.3.0"
  version = "13.3.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java:20.3.0"
  version = "20.3.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/nodejs:9.15.2"
  version = "9.15.2"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/dotnet-core:3.10.0"
  version = "3.10.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/procfile:5.11.4"
  version = "5.11.4"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/web-servers:3.3.3"
  version = "3.3.3"

[lifecycle]
  version = "0.20.19"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "13.3.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "20.3.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/web-servers"
    version = "3.3.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "9.15.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core"
    version = "3.10.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.11.4"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/ubuntu-noble-run:latest"

[stack]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
