description = "Ubuntu 24.04 Noble Numbat base image with buildpacks for Java, Node.js, .NET, Nginx, HTTPD and Procfile"

[build]
  image = "docker.io/paketobuildpacks/ubuntu-noble-build:0.0.47"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java-native-image:13.5.0"
  version = "13.5.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java:20.5.0"
  version = "20.5.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/nodejs:9.16.1"
  version = "9.16.1"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/dotnet-core:3.11.1"
  version = "3.11.1"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/procfile:5.12.0"
  version = "5.12.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/web-servers:3.4.1"
  version = "3.4.1"

[lifecycle]
  version = "0.21.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "13.5.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "20.5.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/web-servers"
    version = "3.4.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "9.16.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core"
    version = "3.11.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.12.0"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/ubuntu-noble-run:latest"

[stack]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
